scriptいい感じにする

diff --git a/scripts/run_once_03_op.sh.tmpl b/scripts/run_once_03_op.sh.tmpl
--- a/scripts/run_once_03_op.sh.tmpl
+++ b/scripts/run_once_03_op.sh.tmpl
@@ -1,9 +1,15 @@
 {{ if eq .chezmoi.os "darwin" -}}
 #!/bin/sh
+set -e
+
+echo "⏩ Start initializing 1Password CLI plugin..."
+
 if type op >/dev/null 2>&1; then
   op plugin init gh
 else
-  echo "1Password CLI is not installed. Cannot install 1Password CLI plugin."
+  echo "❌ 1Password CLI is not installed. Cannot install 1Password CLI plugin."
   exit 1
 fi
+
+echo "✅ Finished initializing 1Password CLI plugin!"
 {{ end -}}
